# hello-go-deploy-aks task-build-push.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-aks

outputs:
- name: dist

run:
  path: ./hello-go-deploy-aks/ci/scripts/build-push.sh
  # args: [-debug]

